Load default data and improve post script for logging
Signed-off-by: Benoit Donneaux <benoit.donneaux@digital-me.nl>

diff --git a/rpm/spec.in b/rpm/spec.in
--- a/rpm/spec.in
+++ b/rpm/spec.in
@@ -297,12 +297,13 @@ install -D -m644 %{SOURCE105} %{buildroot}%{_sysconfdir}/httpd/conf.d/%{name}.co
 pushd %{app_root} > /dev/null
 
 # Prepare log file if required
-LOG_FILE="log/production.log"
+LOG_FILE="%{app_logdir}/production.log"
 if [ -n "${LOG_FILE}" -a ! -f "${LOG_FILE}" ]; then
   touch "${LOG_FILE}"
   chown nobody:nobody "${LOG_FILE}"
   chmod 0644 "${LOG_FILE}"
 fi
+LOG_FILE="%{app_logdir}/install.log"
 
 # No clue why it is needed to unfroze - main post script won't find any gem otherwise!
 scl enable %{ruby_scl} -- bundle config --local frozen 0 > /dev/null
@@ -310,24 +311,24 @@ scl enable %{ruby_scl} -- bundle show > /dev/null
 scl enable %{ruby_scl} -- bundle config --local frozen 1 > /dev/null
 
 # Generate secret token if required
-if [ ! -f "config/initializers/secret_token.rb" ]; then
+if [ ! -f "%{app_etcdir}/initializers/secret_token.rb" ]; then
   echo -n 'Running generate_secret_token task... '
-  RAILS_ENV=production scl enable %{ruby_scl} -- bundle exec rake generate_secret_token > /dev/null 2>&1
+  RAILS_ENV=production scl enable %{ruby_scl} -- bundle exec rake generate_secret_token >> "${LOG_FILE}" 2>&1
   if [ ${?} -eq 0 ]; then
     echo 'ok'
   else
-    echo "error (check logs in $(pwd)/log)"
+    echo "error (check logs in %{app_logdir}/log)"
   fi
 fi
 
 # Create default db file if required
-DB_CONF='config/database.yml'
+DB_CONF="%{app_etcdir}/database.yml"
 DB_ADAPTER="$(sed -n -r -e '/^production:/,/^$/ { s/^\s+adapter:\s*[^-_/\w]?(.+)[^-_/\w]?$/\1/ p }' "${DB_CONF}")"
 DB_FILE="$(sed -n -r -e '/^production:/,/^$/ { s/^\s+database:\s*[^-_/\w]?(.+)[^-_/\w]?$/\1/ p }' "${DB_CONF}")"
 DB_DIR="$(dirname "${DB_FILE}")"
 
 if [ "${DB_ADAPTER}" = 'sqlite3' -a -n "${DB_FILE}" -a ! -f "${DB_FILE}" ]; then
-  [ -d "${DB_DIR}" ] || { mkdir -p "${DB_DIR}" && chown nobody:nobody "${DB_DIR}" && chmod 0755 "${DB_DIR}"; }
+  [ -d "${DB_DIR}" ] || { mkdir -p "${DB_DIR}" && chown root:nobody "${DB_DIR}" && chmod 0775 "${DB_DIR}"; }
   touch "${DB_FILE}"
   chown nobody:nobody "${DB_FILE}"
   chmod 0644 "${DB_FILE}"
@@ -335,18 +336,14 @@ fi
 
 # Initialize or migrate the DB
 echo -n 'Running db:migrate task... '
-RAILS_ENV=production scl enable %{ruby_scl} -- bundle exec rake db:migrate > /dev/null 2>&1
+RAILS_ENV=production scl enable %{ruby_scl} -- bundle exec rake db:migrate >> "${LOG_FILE}" 2>&1
 if [ ${?} -eq 0 ]; then
   echo 'ok'
 else
-  echo "error (check logs in $(pwd)/log)"
+  echo "error (check logs in %{app_logdir}/log)"
 fi
+RAILS_ENV=production scl enable %{ruby_scl} -- bundle exec rake redmine:load_default_data >> "${LOG_FILE}" 2>&1
 popd > /dev/null
-
-
-%postun
-# Remove what's left, mostly vendor/bundle/...
-%{__rm} -rf %{app_root}
 
 
 %files
